### ISSUE TITLE
PreExecutor on IE9 accesses console in unsafe way

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#597] opened 2016-03-28 21:39 UTC
On several [lines](https://github.com/theintern/intern/blob/942baa040a824477f1cda55abd9d029553873db5/lib/executors/PreExecutor.js#L409), the PreExecutor tries to log to `console`.  `console` is not available in IE9 when the debug window is not open, which is causing the PreExecutor to fail on most on demand platforms (which don't have the console open).

I thought we had a way for dealing with messages without writing to console, by interfacing with the reporter.

**Comment by jason0x43** [comment] 2016-03-28 22:06
Gah, I need to modify the self tests to actually exercise Intern itself as part of the testing process (and remember that we're still supporting IE9).

**Comment by jason0x43** [comment] 2016-03-29 00:01
Regarding reporters, the issue is that the reporters haven't loaded at the point suite resolution happens. A better solution would be for the client to only attempt resolution if it was required; then if it fails, the client can throw an error. The tricky part there is how to definitively check for globs in the suites list.

**Comment by jason0x43** [comment] 2016-03-29 04:12
I'm working on some improvements in the `browser-glob` branch. A mid filter is now run before trying to resolve, both in node and the browser. This prevents certain constructs, like 'dojo/has!host-node?fs', from being interpreted as globs, and allows the browser client to skip resolution if nothing needs resolving. Intern will no longer attempt to resolve MIDs involving browser plugins. Resolution failures now show up as session errors, so they're much more visible. IE9 still can't resolve suites, but it now works when none of the suites actually involve glob expressions.

**Comment by jason0x43** [comment] 2016-04-01 19:05
Fixed in https://github.com/theintern/intern/commit/7dc526a786e98f77e5d362e914060656a289bca1

**Closed by jason0x43** 2016-04-01 19:05 UTC
Labels: bug
