### ISSUE TITLE
Running suites in multiple environments

### ISSUE THREAD

**Issue by inad9300** [theintern/intern#885] opened 2018-03-04 15:04 UTC
When running the tests in Chrome alone,
```json
{
    "environments": ["chrome"],
    "suites": ["build/**/*.spec.js"],
    "functionalSuites": ["build/**/*.spec.js", "build/**/*.func.js"],
    "reporters": ["pretty"]
}
```
Both unit and functional tests are executed:
```bash
✓ chrome 64.0.3282.167 on Linux - specification - runs
✓ chrome 64.0.3282.167 on Linux - functional - click button
```
When adding Node.js to the mix,
```json
{
    "environments": ["node", "chrome"],
    "suites": ["build/**/*.spec.js"],
    "functionalSuites": ["build/**/*.spec.js", "build/**/*.func.js"],
    "reporters": ["pretty"]
}
```
The unit tests are only run in Node:
```bash
✓ node - specification - runs
✓ chrome 64.0.3282.167 on Linux - functional - click button
```

Is there a way to ensure that the unit tests are run in both Node and Chrome? Is this the expected behaviour for the given configurations? How so?

**Comment by jason0x43** [comment] 2018-03-05 14:32
In general, unit test suites will run in all specified environments, and functional test suites will run only in Node. However, you're specifying the same set of suites (`build/**/*.spec.js`) for both `suites` and `functionalSuites`, which isn't a support config since the two types of tests will often not be compatible.

**Comment by inad9300** [comment] 2018-03-07 20:52
I do not understand. "Functional tests suites will run only in Node"? I thought it was the other way around, and that functional tests are those which involve interaction with a browser from the point of view of an end user.

My questions are still valid, I think: why is this not supported, and how can one achieve what I'm after (perhaps two different configs, perhaps child configs...)?

In general, I would say if some config is unsupported, validation should be put in place. Is there a plan to improve on this area?

**Comment by jason0x43** [comment] 2018-03-08 02:13
Functional tests work by driving a browser externally. Tests send commands to a WebDriver that tells a browser to do something, but they don't run _in_ the browser. They don't have direct access to `window` or the DOM or any of the things you would normally see in a browser's JS environment.

Running unit tests in multiple environments is supported. As I said, though, by providing the same list of suites to both `suites` and `functionalSuites` you've entered, well, untested territory. Try revising your `suites` list to only contain unit tests, and your `functionalSuites` list to only contain functional suites.

**Comment by jason0x43** [comment] 2018-03-08 02:16
And you're right, Intern could provide more useful errors in certain cases. It wouldn't be perfect, because Intern can't currently tell for certain whether a suite it's given is intended to be a functional or unit test suite, but it could cover some cases.

**Comment by inad9300** [comment] 2018-03-10 17:07
So, by removing the unit tests from the `functionalSuites` option, i.e. by having this configuration
```json
{
    "environments": ["node", "chrome"],
    "suites": ["build/**/*.spec.js"],
    "functionalSuites": ["build/**/*.func.js"],
    "reporters": ["pretty"]
}
```
The unit tests still only run in Node. I get the same result as before:
```bash
✓ node - specification - runs
✓ chrome 64.0.3282.167 on Linux - functional - click button
```

**Comment by jason0x43** [comment] 2019-12-11 14:25
Closing this as overcome by events since it's not reproducible with the current Intern release.

**Closed by jason0x43** 2019-12-11 14:25 UTC
