### ISSUE TITLE
Possible negative values for Suite elapsedTime?

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#469] opened 2015-08-11 19:35 UTC
I saw a negative value for `<testsuite>` time in one of the JUnit reports I generated (`time="-0.025"`).

````
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite name="firefox 37 on any platform" failures="0" skipped="0" tests="4" time="9.87">
    <testsuite name="unit tests" failures="0" skipped="0" tests="2" time="0">
      <testsuite name="unit" failures="0" skipped="0" tests="1" time="0.012">
        <testcase name="onePlusOne" time="0.001" status="0"/>
      </testsuite>
--->      <testsuite name="lib" failures="0" skipped="0" tests="1" time="-0.025">
        <testcase name="formatNumber" time="0" status="0"/>
      </testsuite>
      <testsuite name="cookies" failures="0" skipped="0" tests="0" time="0.003"/>
    </testsuite>
    <testsuite name="Test1" failures="0" skipped="0" tests="1" time="5.525">
      <testcase name="testTabs" time="5.524" status="0"/>
    </testsuite>
    <testsuite name="testPageListService" failures="0" skipped="0" tests="1" time="3.028">
      <testcase name="testPageListService" time="3.027" status="0"/>
    </testsuite>
  </testsuite>
...
````

The specific suite/test responsible for this value is fairly trivial, and is run as a unit test.  So this test is listed in my `suites`, not my `functionalSuites`. This test was part of an entire test run that had:

- 5 suites,
- with one test each,
- running on 6 browsers,
- across 3 selenium nodes.

````
define([
    'intern!object',
    'intern/chai!assert',
    'core/lib'
], function (registerSuite, assert, Lib) {
    registerSuite({
        name: 'lib',

        formatNumber: function () {
            assert.strictEqual(Lib.formatNumber(0), '0', 'Lib.formatNumber(0) is "0"');
        }
    });
});
````

I've taken a look at the code at https://github.com/theintern/intern/blob/3.0.0/lib/Suite.js#L192, https://github.com/theintern/intern/blob/3.0.0/lib/Suite.js#L357 and https://github.com/theintern/intern/blob/3.0.0/lib/Suite.js#L372-L386 and no alarm bells are ringing for me.

#### Reproducibility

... no!  I haven't been able to reproduce, unfortunately.  So I won't be offended if this is taken with some scepticism!

#### Context

- Intern 3.0.0.
- Selenium Hub (2.45.0) running on same machine as where the test was run.
- Firefox 37 on a Selenium node on a Windows 7 VM gave the negative time.
- the tests were actually run against 3 nodes; one on the same machine as the hub, and another Windows 7 VM.

**Comment by csnover** [comment] 2015-08-12 18:05
Are you mocking the Date object or anything in your tests?

**Comment by gitgrimbo** [comment] 2015-08-12 19:07
Nope, I'm not using a mocking library or doing any other form of mocking.

**Comment by csnover** [comment] 2015-09-02 04:54
The only things I can think are that your system happened to run an adjtime call at exactly the wrong moment, or you don’t have ECC RAM and had a memory error, or there’s some crazy bug in the JS engine of Firefox 37. The elapsed time is `Date.now() - startTime`, `startTime` is `Date.now()` which is *guaranteed* to be first, and the value output by the reporter simply takes that value and divides it by 1000. Since this is not reproducible I am going to close this for now but if you can find…something that makes it happen reliably please feel free to post here and I will reopen.

**Closed by csnover** 2015-09-02 04:54 UTC
Labels: needs-info
