### ISSUE TITLE
switchToFrame errors when given string

### ISSUE THREAD

**Issue by maxbeatty** [theintern/intern#1045] opened 2020-01-16 23:33 UTC
## Expected behavior

If the `iframe` I am targeting has an `id` of "card-frame" and a `name` of "card-frame" and can be accessed through `window.frames["card-frame"]`, should I be able to call `switchToFrame("card-frame")`?

## Current behavior

Currently, an error is thrown:

```
InvalidArgument: [POST http://localhost:4444/wd/hub/session/a382b5f9b7e1d73deb28a1e03deb265e/frame / {"id":"card-frame"}] invalid argument: 'id' can not be string
      (Session info: chrome=79.0.3945.117)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'mbeatty-81lvdt.local', ip: '172.28.12.31', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.2', java.version: '11.0.3'
    Driver info: driver.version: unknown
      at Server.post @ node_modules/src/Server.ts:361:16
      at runRequest @ node_modules/src/Session.ts:133:12
      @ node_modules/src/Session.ts:167:44
      at new e @ node_modules/@theintern/common/index.js:16:5068
      at InitializedProxiedSession.Session._delegateToServer @ node_modules/src/Session.ts:110:11
      at InitializedProxiedSession.Session.serverPost @ node_modules/src/Session.ts:179:16
      at InitializedProxiedSession.Session.switchToFrame @ node_modules/src/Session.ts:591:16
      at sessionMethod @ node_modules/src/Command.ts:826:43
      at Command.<anonymous> @ node_modules/src/Command.ts:844:30
      @ node_modules/@theintern/common/index.js:16:7174
      at Command._callSessionMethod @ node_modules/src/Command.ts:811:11
      at Command.switchToFrame @ node_modules/src/Command.ts:1058:16
      @ tests/functional/card.ts:31:7
      at step @ build/tests/functional/card.js:33:23
      at Object.next @ build/tests/functional/card.js:14:53
      @ build/tests/functional/card.js:8:71
      at new Promise @ anonymous
      at __awaiter @ build/tests/functional/card.js:4:12
      at Test.test @ tests/functional/card.ts:25:34
      @ src/lib/Test.ts:266:51
```

## Possible solution

😕 

## Steps to reproduce (for bugs)

Sample code:

```html
<iframe id="card-frame" name="card-frame" frameborder="0" width="100%" scrolling="no" height="17" src="https://remote/iframe"></iframe>
```

```ts
it("should", async test =>
    test.remote
      .get("page.html")
      // Wait for inserted iframe
      .findByCssSelector("iframe#card-frame")
      .end()
      .switchToFrame("card-frame")
```

## Environment

Intern version: 4.7.1
Node version: 13.5.0
NPM version: 6.13.4
Browser version: Chrome 79

## Additional information

Using `switchToFrame(0)` works as expected as well as:

```js
it("should tokenize", async test => {
    const { remote } = test;
    await remote.get("page.html");
    const iframe = await remote.findByCssSelector("iframe#card-frame");
    await remote.switchToFrame(iframe);
```

**Comment by jason0x43** [comment] 2020-01-17 03:57
This is currently the expected behavior. While Selenium and the JsonWireProtocol would allow [string frame identifiers](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidframe) (although they're not clear on what those strings can be), W3C WebDriver, which is the standard followed by modern chromedriver (and soon the rest of the drivers) requires that frame IDs be [numbers or element IDs](https://www.w3.org/TR/webdriver/#switch-to-frame) (which is what you get when you call `switchToFrame with an element). Intern is a fairly thin wrapper on top of webdriver; when it's not fixing a defect in some driver's behavior, it typically just passes data directly to the webdriver.

This does seem like it might be a worthwhile feature enhancement, though. I'm going to close this issue since things are working as intended, and I'll add a note to #1046 about a possible enhancement.

**Closed by jason0x43** 2020-01-17 03:57 UTC
