### ISSUE TITLE
leaveRemoteOpen  = true hangs

### ISSUE THREAD

**Issue by httpete** [theintern/intern#440] opened 2015-07-14 01:50 UTC
I am running with the grunt plugin, and leaveRemoteOpen on a runType of "runner" gives me a message about node hang detected.

**Comment by dylans** [comment] 2015-07-14 14:02
@httpete which version of Intern, 2.2.x or 3.0.rc2?

**Comment by httpete** [comment] 2015-07-14 14:13
3.0 RC3

**Comment by csnover** [comment] 2015-07-27 20:59
Duplicate of #410.

**Closed by csnover** 2015-07-27 20:59 UTC
