### ISSUE TITLE
Issue with Webdriver and Keys?

### ISSUE THREAD

**Issue by EdwardCoyle** [theintern/intern#564] opened 2016-01-04 18:22 UTC
Hi there,

I have a functional test that checks some keyboard functionality against a UI control.  The goal is to make sure that tab-stops on this particular piece of UI work as expected (pressing Tab to go to the next element, Shift+Tab to go to the previous one). It seems to have some issues specifically when running in Firefox:

        'Response to input while in read-only mode': {
          'can be focused/defocused while in read-only mode': function() {
            // Use keyboard to focus/defocus
            return this.remote
              .findById('towns-optgroup-shdo')
                .click()
                .end()
              .pressKeys(['\uE004', '\uE000']) // Tab, then NULL
                .end()
              // Make sure that the current item is focused
              .getActiveElement()
                .getProperty('id')
                .then(function(id) {
                  expect(id).to.equal('readonly-shdo');
                })
                .end()
              // Shift + Tab back to the original dropdown
              .pressKeys(['\uE008', '\uE004', '\uE000']) // Shift, Tab, NULL
                .end()
              .getActiveElement()
                .getProperty('id')
                .then(function(id) {
                  expect(id).to.not.equal('readonly-shdo');
                });
          },

This test passes with flying colors when it's run in Chrome, but fails in Firefox.  When inserting a `.pause(5000)` after the first `.pressKeys()`, I can see that Tab keypress has in fact worked as expected in Chrome, but fails to actually advance to the next element in Firefox.

I'm not sure if this is a bug in Webdriver, or a bug in Intern, or a bug at all, but I figured this would be the place to let you all know about this. Running against Selenium 2.48.2, latest Chrome (47.0.2526.106) and Firefox (43.0.1).

**Comment by csnover** [comment] 2016-01-06 18:36
If it works in one browser but not another, then it is one of two things:

1. an upstream bug with the driver for the broken browser.
2. a race condition in your page code or test code that is only triggered in one browser. (For example, if you disable keyboard interaction during an Ajax request or similar.)

I know tabbing has worked for Firefox users in the past so I would recommend trying older versions of Selenium & Firefox until you find one that isn’t broken, then [report the regression upstream](https://github.com/SeleniumHQ/selenium/issues). Since this is not an Intern bug I will close this issue. Thanks!

**Closed by csnover** 2016-01-06 18:36 UTC
