### ISSUE TITLE
Non-printable keys are entered into inputs

### ISSUE THREAD

**Issue by schontz** [theintern/intern#1044] opened 2019-08-21 21:41 UTC
Test:

```js
page
  .findByCssSelector('input')
  .then(leftClick)
  .pressKeys('jon')
  .pressKeys(keys.ARROW_LEFT)
  .pressKeys('h')
  .executeAsync(function (done) {
    done(document.querySelector('input').value);
  }).then(function (value) {
    assert.equal(value, 'john');
  });
```
Fails with something like:
```
A jon[]h
E john
```
Where `[]` is a rectangle character.

* Browser: Chrome 76
* OS: Windows 10
* Intern: 4.4.3

**Comment by jason0x43** [comment] 2020-01-16 21:16
This is a duplicate of #1038. Intern uses simulated events for webdrivers that default to W3C mode, which has no `/keys` command, and apparently that needs some work.

**Closed by jason0x43** 2020-01-16 21:16 UTC
Labels: bug, webdriver
