### ISSUE TITLE
Successful test fails because of timeout

### ISSUE THREAD

**Issue by tplesnar** [theintern/intern#521] opened 2015-10-27 15:41 UTC
I created this repo to help debug:
https://github.com/tplesnar/Intern-bug-investigation

As a starter, I am using yadda and https://github.com/xdissent/intern-yadda-loader 

Steps to reproduce:
Of course 
`npm install` don't mind the `UNMET PEER DEPENDENCY yadda@0.16.0` seems to be a npm bug
Start your local selenium server and update your platform if you're not on a mac https://github.com/tplesnar/Intern-bug-investigation/blob/master/test/intern.js#L4

Then run `npm test` Here is the yadda file describing the steps:

```
Feature: I want to have a suite reporting properly errors

Scenario: Simple test should reports errors as and when they occur
Given I open the url "http://theintern.github.io/"
And I execute async remote function
And I execute async remote function and fail
And the element "h1 small.subtitle" is visible
``` The step `And I execute async remote function` should pass, but in console:

```
✓  chrome on MAC - I want to have a suite reporting properly errors - Simple test should reports errors as and when they occur - Given I open the url "http://theintern.github.io/"
× chrome on MAC - I want to have a suite reporting properly errors - Simple test should reports errors as and when they occur - And I execute async remote function
CancelError: Timeout reached on chrome on MAC - I want to have a suite reporting properly errors - Simple test should reports errors as and when they occur - And I execute async remote function
at null.<anonymous>  <node_modules/intern/lib/Test.js:162:20>
at Timer.listOnTimeout  <timers.js:92:15>
× chrome on MAC - I want to have a suite reporting properly errors - Simple test should reports errors as and when they occur - And I execute async remote function and fail
Too big
``` I placed some other yadda files for you to fiddle if needed.

**Comment by csnover** [comment] 2015-10-28 23:37
By default test timeout is 30 seconds, this can be modified by the [`defaultTimeout` configuration option](https://theintern.github.io/intern/#option-defaultTimeout) if you think it’s too slow. Why do you think the test is successful?

**Comment by tplesnar** [comment] 2015-10-29 09:21
Test default timeout is ok for my test, as the async code should execute in less than 2 seconds. 

My concerns lies here:
```
× chrome on MAC - I want to have a suite reporting properly errors - Simple test should reports errors as and when they occur - And I execute async remote function
CancelError: Timeout reached on chrome on MAC - I want to have a suite reporting properly errors - Simple test should reports errors as and when they occur - And I execute async remote function
  at null.<anonymous>  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout  <timers.js:92:15>
```
This step throw no error or wrong assertion and so returns properly (never goes into this `if` https://github.com/tplesnar/Intern-bug-investigation/blob/master/test/support/helper/checkGUILoaded.js#L37-L43 ). From my understanding of intern, this step should pass, but it doesn't because of timeout. Moreover when you consider that this step https://github.com/tplesnar/Intern-bug-investigation/blob/master/test/support/helper/open.js looks very similar to the one timing out and passes properly. The next step `And I execute async remote function and fail`, supposed to fail, properly catches the first throw and logs `Too big`.

**Comment by jason0x43** [comment] 2017-11-08 21:49
There have been a number of improvements to how Intern handles async test timeouts and manages remote tests since this issue was originally filed. I'm closing it for now, but feel free to reopen if the issue is still relevant.

**Closed by jason0x43** 2017-11-08 21:49 UTC
Labels: needs-info
