### ISSUE TITLE
Not able to run the functional test cases parallel on sauce labs.

### ISSUE THREAD

**Issue by MohanKalidindi** [theintern/intern#567] opened 2016-01-06 18:35 UTC
Description:

Steps to reproduce:

1. Run the functional test cases on sauce labs
2. functional test cases are running sequentially on the same browser, ideally it should open an multiple browsers to execute parallel

Expected result: It should run parallel.
Actual result: It is running sequentially 

Intern version: 3.0.6

Any additional information:

**Comment by csnover** [comment] 2016-01-06 18:37
Duplicate of https://github.com/theintern/intern/issues/546.

**Closed by csnover** 2016-01-06 18:37 UTC
