### ISSUE TITLE
Intern client crashes when running large amount of tests

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#479] opened 2015-08-29 13:47 UTC
### Overview

Intern client crashes when running large amount of tests. I can see it crashing with test files count more than 3000 (I was able to run it ok with 2000 files). It displays error message *Failed to load module test/unit/example02048Tests from {mypath}//test/unit/example02048Tests.js* although mentioned file exists on disk.

### Console output

```console
Error: Failed to load module test/unit/example02048Tests from {mypath}//test/unit/example0204
8Tests.js (parent: test/config/.generated/all.js)
  at <node_modules\intern\node_modules\dojo\loader.js:490:27>
  at <fs.js:263:20>
  at FSReqWrap.oncomplete  <fs.js:95:15>
npm ERR! Test failed.  See above for more details.
```

### Environment details:

Intern: 3.0.0
node.js: v0.12.7
Platform: Windows 7

### Steps to reproduce

1. Create the same file structure as shown below
2. npm install
3. Edit file *test/support/prepare.js* if you wish to increase test files count
4. npm test

### File structure

*package.json*
```json
{
  "name": "internClientCrashesWhenExecutingLargeNumberOfTests",
  "version": "1.0.0",
  "description": "Intern client crashes when executing large number of tests",
  "author": "Bartosz Kaczorek",
  "private": true,
  "scripts": {
    "pretest": "node test/support/prepare.js",
    "test": "node_modules/.bin/intern-client config=test/config/intern.js"
  },
  "dependencies": {
    "fs-extra": "^0.23.1",
    "glob": "^5.0.14",
    "intern": "^3.0.0",
    "mkpath": "^0.1.0",
    "underscore": "^1.8.3",
    "underscore.string": "^3.2.0"
  }
}
```

*test/resources/exampleTests.js*
```javascript
define(['module',
	'intern!bdd',
	'intern/chai!expect'], function (module, bdd, expect) {
	"use strict";

	bdd.describe(module.id, function () {

		bdd.describe('When adding two numbers', function () {
			var result = null;

			bdd.before(function () {
				result = 2 + 3;
			});

			bdd.it('Then result should contain sum of them', function () {
				expect(result).to.equal(5);
			});
		});

		bdd.describe('When multiplying two numbers', function () {
			var result = null;

			bdd.before(function () {
				result = 4 * 5;
			});

			bdd.it('Then result should contain product of them', function () {
				expect(result).to.equal(20);
			});
		});

	});
});
```

*test/support/TestsGenerator.js*
```javascript
var util = require('util');
var fse = require('fs-extra');
var pad = require('underscore.string/pad');

function ExampleGenerator(config) {

	this.generate = function(count) {
		var self = this;
		fse.emptyDirSync(config.outputDir);
		for (var i=1; i<=count; i++) {
			var fileName = util.format('example%sTests.js', pad(i, 5, '0'));
			var outputFilePath = config.outputDir + '/' + fileName;
			fse.copySync(config.exampleTestFilePath, outputFilePath);
		}
	};
	
};

module.exports = ExampleGenerator;
```

*test/support/TestsGlobber.js*
```javascript
var util = require('util');
var glob = require('glob');
var path = require('path');
var mkpath = require('mkpath');
var fs = require('fs');

function TestsGlobber(config){
	
	this._config = config;
	
	this.run = function() {
		
		var files = glob.sync(this._config.searchPattern).map(function (filename) {
			return filename.replace(/\.js$/, '');
		});

		var content = util.format('define(%s);\n', JSON.stringify(files, null, 4));
		mkpath.sync(path.dirname(this._config.outputFilePath));

		fs.writeFileSync(this._config.outputFilePath, content, {
			encoding : 'utf-8'
		});

		console.log('File saved to: %s', this._config.outputFilePath);
	};
	
}

module.exports = TestsGlobber
```

*test/support/prepare.js*
```javascript
var TestsGenerator = require('./TestsGenerator');
var TestsGlobber = require('./TestsGlobber');

var generator = new TestsGenerator({
	exampleTestFilePath : 'test/resources/exampleTests.js',
	outputDir : 'test/unit'
});
var globber = new TestsGlobber({
	searchPattern : 'test/unit/**/*Tests.js',
	outputFilePath : 'test/config/.generated/all.js'
});

generator.generate(3000);
globber.run();
```

*test/config/intern.json*
```json
{
	"proxyPort": 9000,
	"proxyUrl": "http://localhost:9000/",
	"maxConcurrency": 1,
	"tunnelOptions": {
		"hostname": "localhost",
		"port": 4444
	},
	"loaderOptions": {
		"packages": []
	},
	"suites": ["test/config/.generated/all.js"],
	"functionalSuites": [],
	"excludeInstrumentation": "(node_modules|test)[\\\\/]"
}
```

*test/config/intern.js*
```javascript
define(['intern/dojo/text!./intern.json'], function (configJson) {
	var config = JSON.parse(configJson);
	config.excludeInstrumentation = new RegExp(config.excludeInstrumentation);
	return config;
});
```

**Comment by csnover** [comment] 2015-09-01 08:45
Duplicate of #478.

**Closed by csnover** 2015-09-01 08:45 UTC
