### ISSUE TITLE
add async support to suite object

### ISSUE THREAD

**Issue by jstrimpel** [theintern/intern#289] opened 2014-10-15 01:24 UTC
For certain use cases it makes sense to have the convenience of `this.async` in the suite object in addition to the test object. I would like to add it as an enhancement. 

Currently the code is in https://github.com/theintern/intern/blob/master/lib/Test.js#L69. My first inclination is to put it in a module named `lib/asnyc.js` and include it `lib/Test.js` and `lib/Suite.js`. Is there another pattern, naming convention, etc. that you would prefer?

**Comment by herby** [comment] 2015-09-11 17:39
Yeah, I want be able to `this.async` in {before,after}{,Each} as well.

**Comment by jason0x43** [comment] 2016-01-06 15:59
Does anyone have an example of how this feature would be used? Suites are already run asynchronously, and `setup` and `teardown` now support async operations if a Promise is returned. Is the goal just to provide one of Intern's augmented Deferreds in the Suite lifecycle methods?

**Comment by herby** [comment] 2016-01-06 16:02
Oh, if `setup` and `teatDown` are fine by returning `Promise`, than I am ok with that.

**Comment by csnover** [comment] 2016-01-06 16:09
@jason0x43 it’s for convenience so people do not need to create their own promises to do async stuff in suite methods. it also helps to provide a more consistent api for test suites (i.e. there should be no case where `this.async` is available in one context and not in another context, even though they both do the same kind of async operation).

**Comment by jason0x43** [comment] 2016-01-06 16:34
Do they actually do the same operation? I mean, I can see value in using `this.async` to get a promise in a suite lifecycle method, but would `async`'s arguments be useful in a Suite context?

**Comment by csnover** [comment] 2016-01-06 16:40
yes, i think you would want to be able to avoid hangs caused by your suite methods never resolving too.

**Comment by csnover** [comment] 2016-01-06 16:43
i mean, the Suite ones are slightly different because they are different for each lifecycle method, whereas the Test one is directly associated with just the one test method used by the Test object. but to the end-user they are exposed the same way.

**Comment by jason0x43** [comment] 2016-01-06 16:55
So saying `this.async(1000)` in a suite's `setup` method would put a 1000 second timeout on just the setup method, while calling it in a `beforeEach` would do so for each call of `beforeEach`?

**Comment by csnover** [comment] 2016-01-06 17:04
well, 1000ms at least :)

it is just a convenience function to prevent boilerplate like this:

```js
setup() {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => { reject(new Error("Timed out")); }, 5000);
    doTheActualWork().then(
      (value) => { clearTimeout(timer); resolve(value); },
      (error) => { clearTimeout(timer); reject(error); }
    );
  });
},
beforeEach() {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => { reject(new Error("Timed out")); }, 5000);
    doTheActualWork().then(
      (value) => { clearTimeout(timer); resolve(value); },
      (error) => { clearTimeout(timer); reject(error); }
    );
  });
},
…
```

**Comment by jason0x43** [comment] 2016-01-06 17:05
Oh yeah, ms. :)  In any case, that makes sense.

**Comment by sholladay** [comment] 2016-01-06 21:54
I primarily want this for the Deferred sugar. Here is an example of how I would like to use it.
````javascript
define(
    [
        'intern!tdd',
        'request'
    ],
    function (tdd, request) {

        var suite  = tdd.suite,
            test   = tdd.test,
            before = tdd.before;

        suite('foo', function () {

            var qaData;

            before(function () {

                var dfd = this.async(
                    // Error out and do not run the suite if we cannot get any
                    // data from QA services in a reasonable amount of time.
                    1000
                );

                request(
                    'https://qa.company.com/data.json',
                    dfd.callback(function (error, data) {
                        if (error) {
                            throw error;
                        }

                        qaData = JSON.parse(data);

                        assert.isTrue(qaData.everythingIsFine);
                    }
                );
            });

            test('bar', function () {
                // make use of all the juicy qaData
            });
        });
    }
);
````

This is a contrived and not very fancy example, but you will notice that it is nearly identical to what is [in the user guide](https://theintern.github.io/intern/#async-tests) for Test#async(). I feel that this is particularly useful for functional tests, which is where I plan to use it first. Since WebDriver tests are prone to failure cascades even if you are careful, it is useful to avoid doing any unnecessary work wherever possible there. Async suites help achieve that goal by making non-trivial network and file I/O more manageable, enabling you to inspect your surroundings before proceeding, and potentially bailing with more user-friendly errors if all is not well.

**Closed** 2016-03-23 20:21 UTC
Labels: d-medium, enhancement, help-wanted
