### ISSUE TITLE
Scroll performance documentation site (probably related to scroll listeners)

### ISSUE THREAD

**Issue by JustGoscha** [theintern/intern#671] opened 2016-09-19 14:57 UTC
Hi, I'm testing on Mac OS 10.11.6 on latest Chrome (53.0.2785.116) and am experiencing quite heavy slow downs during scrolling on your documentation page. 

It seems like there is a scroll listener at work.

**Comment by sholladay** [comment] 2016-10-05 05:17
The only place I see `addEventListener` at all is in [css/main.js](https://github.com/theintern/theintern.github.io/blob/68b73bdb6a1b71fe46381177f0d06ccdf027b057/css/main.js) and that doesn't have any `scroll` listeners.

Without more information, I am going to guess it is caused by a browser extension you are using. Try Incognito mode.

**Comment by jason0x43** [comment] 2016-10-05 12:55
There is actually a scroll listener in `css/main.js` that's used to sync the doc position with the contents on the left. I don't believe there are any issues with current Chrome (I'm using Chrome 53 and Safari 10 on Mac OS 10.12), so @sholladay is likely correct that the issue is a conflict between the code on the doc page and a browser extension. It'd be interesting to narrow down the issue, if you were up for some quick testing.

**Comment by sholladay** [comment] 2016-10-05 17:45
@jason0x43 one thing that could help would be to turn on `passive` mode for event listeners wherever possible. However, this is incompatible with the use of `preventDefault()` so something would need to be done about that.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners

**Comment by aFarkas** [comment] 2016-10-16 14:23
There are multiple things that can be improved here, but probably the most heavy problem is the fact that the [following lines](https://github.com/theintern/intern/blob/gh-pages/css/main.js#L89-L91) are dead code. (i.e.: `lastHash` is always undefined.) Therefore you are running unneeded DOM mutations with every scroll.

**Comment by jason0x43** [comment] 2019-12-12 19:20
Closing this as it refers to the old site, and the current site doesn't appear to have this issue.

**Closed by jason0x43** 2019-12-12 19:20 UTC
