### ISSUE TITLE
Any way to specify a base url for functional test cases?

### ISSUE THREAD

**Issue by jiayexie** [theintern/intern#829] opened 2017-10-29 01:15 UTC
Hi, I'm trying to write an e2e test and I need different urls for different configs (local, dev, prod, etc.). Is there an way to specify the base url in the config json file and access it from test cases?

Thanks!

**Comment by jason0x43** [comment] 2017-11-06 14:05
There is a `functionalBaseUrl` config property. This sets the base URL that will be used for any relative addresses in functional tests.

**Comment by jason0x43** [comment] 2017-11-20 14:35
Closing this since there hasn't been any update. Feel free to reopen if the issue isn't resolved with `functionalBaseUrl`.

**Closed by jason0x43** 2017-11-20 14:35 UTC
