### ISSUE TITLE
Highly out-of-order message transmission may hang test runner

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#466] opened 2015-08-10 03:20 UTC
The https://github.com/dojo/core unit tests have been hanging relatively frequently in IE9, and occasionally in other browsers.

The main issue, particularly for IE9, is that the WebDriver reporter sends out a flood of requests while unit tests are running, and IE doesn't always service the requests in the order in which they were submitted. IE9 will service at most 12 simultaneous POSTs (this was observed both from within IE and from the test server) and then wait for at least one of them to complete before servicing the next pending request. If 12 non-sequential requests are being serviced, which was seen to happen relatively frequently, the testing system hangs because Intern's proxy never responds to the client.

One fix is to limit the number of requests that can be issued at any one time. `lib/Proxy.js` already uses a queue for `shouldWait` requests. Extending the queue's use to all requests takes care of the problem. The downside to this solution is reduced performance. The dojo2-core tests normally take 2-2.5 minutes to run on OS X FF 38 (this browser was used for performance testing because it was also the target of a buffering-related fix described below). When the number of simultaneous requests is limited to 4, the tests take around 4.25 minutes. Increasing this limit to 12 brings the test time back into the 2.5-3 minute range. I've implemented this approach in https://github.com/jason0x43/intern/tree/limit-requests.

Another possible fix is to only have a single active request from the WebDriver reporter at a time, and to send all generated WebDriver messages in batches. When new messages are generated, they're either sent immediately or queued. When a send completes, if any messages are queued another send is initiated for all currently queued messages. Doing this brings the runtime back down to the 2.5 minute range. This method should also perform better on higher latency networks, since a couple of large requests should complete significantly faster than several thousand tiny ones. I've implemented this approach in https://github.com/jason0x43/intern/tree/buffer-messages.

Buffering uncovered another issue. When using a buffering approach, where POSTs from the browser could be in the 1.5+ MB range, OS X FF would reload the test page during the testing process, causing repeated message sequence number and failing the session. Selenium would also occasionally return a page load timeout error. The source of both of these turned out to be due to how Selenium tracks page loads. When ClientSuite loads `client.html`, Selenium doesn't recognize the page as having been loaded until some arbitrary point during the testing process, always just after some other request has completed. If the client starts sending a large request before Selenium has decided the page is loaded, the page load won't be recognized until after the large request completes. If the request is a couple of megabytes, it can take long enough to trigger a page load timeout. The solution in this case is to modify `client.html` to load the test suites in a `window.onload` callback. This guarantees that Selenium will recognize that the test page has been loaded as soon as it actually has, and also avoids random page load timeouts during the testing process. My `buffer-messages` branch mentioned above contains this modification.

So, should we implement request limiting or buffering, and/or modify `client.html` to use `onload`? Are there some downsides that I've missed?

**Comment by csnover** [comment] 2015-08-10 03:49
I actually think multiple of these things should be implemented, since batching is probably going to be a great performance improvement on its own! (Reducing the request size is also something that we should do in the future by introducing synthetic unique IDs for each node.) As far as the intermittent hangs caused by out-of-order requests goes, `lib/Proxy.js` really just needs to blast back 204 responses immediately if the client reporter config `waitForRunner` is not true (just like it did in Intern 2). The thing about Firefox and onload is a great catch too, I am sure that was a pain to debug, so definitely will want to fix that too.

I think the best initial approach will be to fix Proxy to respond immediately, since this will unstuck some things, and add the onload fix, since that probably will impact people with large test suites. Limiting the requests should not be necessary but could also be added if desired. Maybe it’s also worth adding a timeout-retry to the requests.

**Comment by csnover** [comment] 2015-09-02 04:56
I’m going to close this as resolved in 3.0.1 (since it is…resolved in 3.0.1 :)), could you open some additional tickets for future enhancements to improve efficiency if you think it is still worth it? Thanks!

**Closed by csnover** 2015-09-02 04:56 UTC
