### ISSUE TITLE
Add an option to run multiple concurrent tests

### ISSUE THREAD

**Issue by AmirTugi** [theintern/intern#901] opened 2018-04-26 10:32 UTC
I would like to suggest a feature, which I think could be really nice as an out-of-the-box feature.
What do you say about being able to decide how many "runner"s you'll run when you run `intern`?

I think being able to run more than 1 test at a time is crucial for develocity.

I need it for Selenium, so maybe [Selenium-Grid](https://www.seleniumhq.org/docs/07_selenium_grid.jsp) could be helpful here.
But I think that general solution would be sweet.

As a workaround for now, I am working on running multiple intern instances and controlling and managing them by myself. Not ideal, but working (will try to release this soon so other people could use it as well).

**Comment by jason0x43** [comment] 2018-04-26 13:12
I agree, this would be pretty nice. It's a feature we've been interested in for a while (#546, #779), but nothing has been implemented yet.

Selenium tests are the exception. Intern already runs WebDriver tests in different browsers concurrently, up to [maxConcurrency](https://theintern.io/docs.html#Intern/4/api/lib%2Fcommon%2Fconfig/maxconcurrency) sessions.

**Comment by jason0x43** [comment] 2019-12-11 13:40
Closing as duplicate of #546

**Closed by jason0x43** 2019-12-11 13:40 UTC
